# Hugo Configuration
title: 'Andreea Elena Bodea'
baseURL: 'https://andreea-bodea.github.io/'

defaultContentLanguage: en
hasCJKLanguage: false
removePathAccents: true

build:
  writeStats: true
enableGitInfo: false
summaryLength: 40
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

outputs:
  home: [HTML, RSS]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture

timeout: 600000

taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types

markup:
  highlight:
    lineNos: false

sitemap:
  changefreq: monthly
  priority: 0.5
